[workloads]
search_path = "workloads/src"
tests = [
  "mvin_mvout_test-singlecore-baremetal",
  "mvin_mvout_stride_test-singlecore-baremetal",
  "transpose_test-singlecore-baremetal",
  "transpose_16xn_test-singlecore-baremetal",
  "fp2int_test-singlecore-baremetal",
  "int2fp_test-singlecore-baremetal",
  "quant_scale_granularity_test-singlecore-baremetal",
  "matrix_test-singlecore-baremetal",
  "matrix_matmul_16x16_ones-singlecore-baremetal",
]
